[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints={eth-sepolia="https://eth-sepolia.g.alchemy.com/v2/xrujstdZvh7yJvOZCmlZz5G5BQaiIhwk",base-sepolia="https://base-sepolia.g.alchemy.com/v2/xrujstdZvh7yJvOZCmlZz5G5BQaiIhwk"}
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts",
    "ccip/=lib/ccip/",
    "chainlink-local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
